@startuml
title アルゴリズム行進（先頭）

start

repeat
    :一歩進んで前ならえ;
    :一歩進んで偉い人;
    :ひっくり返ってぺこりんこ;
    :横に歩いてキョロキョロ;
    :ちょっとここらで平泳ぎ;
    :ちょっとしゃがんでで栗拾い;
    :空気入れますシューシュー;
    :空気が入ってピューピュー;
repeat while (進んだ歩数 >= 16) is (No)
->Yes;

:そろそろ終わりかな;
:そろそろ終わりかな;
:そろそろ終わりかな;
:終わり;

stop
@enduml
